### ISSUE TITLE
Registro de usuarios

### ISSUE THREAD

**Issue by KnowMadDev** [CodeSystem2022/LosBorbocoders_ProyectoFinal#2]
1. Crear una función que solicite al usuario un nombre de usuario o email, telefono y contraseña
2. Crear un servicio que verifique y almacene esta información en la base
3. Crear una tabla para almacenar los usuarios

**Comment by javigoall** [comment]
Realizado. Con cambios, ahora se solicita solamente user, password, relacionado con account,
