### ISSUE TITLE
1.1 Registro de usuarios: Crear una función que solicite al usuario un nombre de usuario o email, telefono y contraseña

### ISSUE THREAD

**Issue by KnowMadDev** [CodeSystem2022/LosBorbocoders_ProyectoFinal#3]

**Comment by ojedam13** [comment]
Se creo el registro de usuario con exito


![Image](https://github.com/CodeSystem2022/LosBorbocoders_ProyectoFinal/assets/80652770/511aafe6-60d1-4087-8fc5-54df26a381e6)
